### PR TITLE
Allow setting kubeconfig from variable

### PR DESCRIPTION
**Pull request by Chraneco**
With this change it is possible to use a kubeconfig which is available in a variable instead of a file.
This enables you to e.g. store the kubeconfig in Vault and use it directly in the resource like so:

```
- put: helm-release
  params:
    chart: src/chart
    kubeconfig: ((kubeconfig))
```

### CODE REVIEW

**Comment by Typositoire** [comment]
I'll be looking at it later today. Sorry vacations, bad timing.

**Comment by Chraneco** [comment]
Thanks! No worries!

**Comment by Typositoire** [comment]
Could you please bump the version to 1.19.0 ? Then I'll merge it.

**Comment by Chraneco** [comment]
Sure, done!

**Review by Typositoire — APPROVED** [review]

**Pull request merged**
