### PR TITLE
Optional Workload Identity flag for GKE clusters

### PR DESCRIPTION
**Pull request by michyliao**
Optional flag to auth with workload identity for GKE clusters. Also fixed up some typos in the README.md

### CODE REVIEW

**Review by Typositoire — APPROVED** [review]
LGTM, CI will complain about version, please bump the minor version.

**Comment by Typositoire** [comment]
My concourse is broken right now. I'll merge it ASAP. But LGTM

**Comment by michyliao** [comment]
@Typositoire Was about to comment that the check is hanging! Thanks for the fast review and reply 🙏

**Comment by Typositoire** [comment]
Concourse: Version bump found.

**Review by Typositoire — APPROVED** [review]

**Pull request merged**
