### PR TITLE
Remove dry-run flag from helm diff when debug is on

### PR DESCRIPTION
**Pull request by declement**
### Description

This change aims to remove the `--dry-run` flag from the `helm diff` command when `debug` and `show_diff` are true, in order to allow showing changes in logs without actually performing a release.

Currently, when these two parameters are combined, the `helm diff --dry-run` command performed actually _shows the diff as if it was installed_. It means the diff is shown as if all Kubernetes manifests were to be installed, which is very similar to the behavior of the `debug` parameter alone.

### CODE REVIEW

**Comment by Typositoire** [comment]
Concourse: Version bump did not happen. v1.29.0 is the same as v1.29.0

**Comment by Typositoire** [comment]
Concourse: Version bump found.

**Comment by Typositoire** [comment]
Can you post an example of both output?

1- with --dry-run
2- with --debug

If I get it correctly, you're saying those are equivalent. It's 100% possible but I won't be able to test before tomorrow. If you would post example that'd be awesome!

**Comment by declement** [comment]
Before this change, the two following commands are run successively when `show_diff` and `debug` are set to true:

```
$ helm diff --namespace test --dry-run test ./test                        
Command "helm diff" is deprecated, use "helm diff upgrade" instead
test, test, Pod (v1) has been added:
- 
+ # Source: tests/templates/pod.yaml
+ apiVersion: v1
+ kind: Pod
+ metadata:
+   name: test
+   annotations:
+     new: test
+ spec:
+   containers:
+   - name: test
+     image: busybox:latest
+     command: ["/bin/sh"]
+     args: ["sleep 5000"]

$ helm upgrade --install --namespace test --create-namespace test --debug --dry-run ./test
history.go:56: [debug] getting history for release test
upgrade.go:144: [debug] preparing upgrade for test
upgrade.go:152: [debug] performing update for test
upgrade.go:315: [debug] dry run for test
Release "test" has been upgraded. Happy Helming!
NAME: test
LAST DEPLOYED: Fri Feb 24 12:32:07 2023
NAMESPACE: test
STATUS: pending-upgrade
REVISION: 4
TEST SUITE: None
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
{}

HOOKS:
MANIFEST:
---
# Source: tests/templates/pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: test
  annotations:
    new: test
spec:
  containers:
  - name: test
    image: busybox:latest
    command: ["/bin/sh"]
    args: ["sleep 5000"]h
```

With this change, the two following commands are run successively when `show_diff` and `debug` are set to true:

```
$ helm diff --namespace test test ./test  
Command "helm diff" is deprecated, use "helm diff upgrade" instead
test, test, Pod (v1) has changed:
  # Source: tests/templates/pod.yaml
  apiVersion: v1
  kind: Pod
  metadata:
    name: test
+   annotations:
+     new: test
  spec:
    containers:
    - name: test
      image: busybox:latest
      command: ["/bin/sh"]
      args: ["sleep 5000"]
      
 $ helm upgrade --install --namespace test --create-namespace test --debug --dry-run ./test
history.go:56: [debug] getting history for release test
upgrade.go:144: [debug] preparing upgrade for test
upgrade.go:152: [debug] performing update for test
upgrade.go:315: [debug] dry run for test
Release "test" has been upgraded. Happy Helming!
NAME: test
LAST DEPLOYED: Fri Feb 24 12:32:07 2023
NAMESPACE: test
STATUS: pending-upgrade
REVISION: 4
TEST SUITE: None
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
{}

HOOKS:
MANIFEST:
---
# Source: tests/templates/pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: test
  annotations:
    new: test
spec:
  containers:
  - name: test
    image: busybox:latest
    command: ["/bin/sh"]
    args: ["sleep 5000"]
```

**Comment by Typositoire** [comment]
Wow it took me a while to understand!!! I get it! Thanks for the explanation 😊

**Review by Typositoire — APPROVED** [review]

**Pull request merged**
