### PR TITLE
Gcloud upgrade 416

### PR DESCRIPTION
**Pull request by jvandenhoek**
Build is failing because gcloud was too old:

```
#7 8.811 Traceback (most recent call last):
#7 8.811   File "/usr/local/gcloud/google-cloud-sdk/bin/bootstrapping/install.py", line 12, in <module>
#7 8.811     import bootstrapping
#7 8.811   File "/usr/local/gcloud/google-cloud-sdk/bin/bootstrapping/bootstrapping.py", line 46, in <module>
#7 8.812     from googlecloudsdk.core.updater import update_manager
#7 8.812   File "/usr/local/gcloud/google-cloud-sdk/lib/googlecloudsdk/core/updater/update_manager.py", line 39, in <module>
#7 8.812     from googlecloudsdk.core.console import progress_tracker
#7 8.812   File "/usr/local/gcloud/google-cloud-sdk/lib/googlecloudsdk/core/console/progress_tracker.py", line 631, in <module>
#7 8.812     class _BaseStagedProgressTracker(collections.Mapping):
#7 8.812 AttributeError: module 'collections' has no attribute 'Mapping'
```

Updating to gcloud version 416 fixes (built locally successfully). Thanks!

### CODE REVIEW

**Review by Typositoire — APPROVED** [review]

**Comment by jvandenhoek** [comment]
Fixing conflicts ASAP!

**Comment by Typositoire** [comment]
You need to merge master back I think

**Comment by jvandenhoek** [comment]
Yes indeed! doing so now.

**Comment by Typositoire** [comment]
No stress lol

**Comment by Typositoire** [comment]
Concourse: Version bump found.

**Comment by jvandenhoek** [comment]
There we go, all resolved :)

**Pull request merged**
