### PR TITLE
Update  to  Helm 3.8.0  

### PR DESCRIPTION
**Pull request by cqwense**
My personal goal for this is to  get the `--fiilter` option for the `helm test` functionality.

### CODE REVIEW

**Comment by cqwense** [comment]
PS - feel free to squash.

**Review by Typositoire — APPROVED** [review]

**Comment by Typositoire** [comment]
Concourse: Version bump found.

**Comment by Typositoire** [comment]
FYI, if you push commits that are older than the last merged PR, concourse won't trigger :(

**Comment by Typositoire** [comment]
1.22.0 build is broken Oo

**Comment by Typositoire** [comment]
See https://github.com/Typositoire/concourse-helm3-resource/pull/76

**Pull request merged**
