### PR TITLE
Fix asset/check  && Add helm test functionality

### PR DESCRIPTION
**Pull request by cqwense**
adds asset/out parameter functionality

test: true
test_logs: true

inherits existing asset/out functionality:

debug
timeout
namespace
release

---------

Currently check is failing with a syntax-error / missing-whitespace , which causes the 

echo '[]' | jq . >&3

to always trigger.

--

Besides that, it is valuable for check to fail when applicable , for instance if you setup a git resource pointing to a repository that exists, but a branch that doesn't - the check should fail.  In turn, if we configure a helm resource that gets passed 

setup_resource $payload

but fails to find a deployed revision of $release in $namespace then check should fail.

these changes to check go through every possible configuration location for each $namespace and $release ( in the same way assout/out does ) and tries to find the latest deployed revision number.

All of my use cases have namespace and release defined in resource source params, so if anyone uses put params I could use the help testing -- Either way I think its an improvement upon the existing.

### CODE REVIEW

**Comment by Typositoire** [comment]
I will summit this to test on one of our pet project. We do use a lot of put namespace release and almost nothing is using source params. Let see if this works.

**Comment by Typositoire** [comment]
This should be merged today

**Comment by cqwense** [comment]
hey there - I think something may have gone wrong with the build ? - when I
pull the v1.12.0 from docker hub I get:

selected worker: concourse-worker-1
waiting for docker to come up...
Pulling typositoire/concourse-helm3-resource@sha256
:0a204eb36cf061e143aff6871a2a11446447e285febead0dfb190c535b06d753...
Error response from daemon: manifest for
typositoire/concourse-helm3-resource@sha256:0a204eb36cf061e143aff6871a2a11446447e285febead0dfb190c535b06d753
not found: manifest unknown: manifest unknown
Pulling typositoire/concourse-helm3-resource@sha256:0a204eb36cf061e143aff6871a2a11446447e285febead0dfb190c535b06d753
(attempt 2 of 3)...
Error response from daemon: manifest for
typositoire/concourse-helm3-resource@sha256:0a204eb36cf061e143aff6871a2a11446447e285febead0dfb190c535b06d753
not found: manifest unknown: manifest unknown
Pulling typositoire/concourse-helm3-resource@sha256:0a204eb36cf061e143aff6871a2a11446447e285febead0dfb190c535b06d753
(attempt 3 of 3)...
Error response from daemon: manifest for
typositoire/concourse-helm3-resource@sha256:0a204eb36cf061e143aff6871a2a11446447e285febead0dfb190c535b06d753
not found: manifest unknown: manifest unknown
Failed to pull image typositoire/concourse-helm3-resource@sha256
:0a204eb36cf061e143aff6871a2a11446447e285febead0dfb190c535b06d753.
fetching the image did not produce a volume

for craps and giggles I tried pull from docker hub locally, retagging it,
pushing it somewhere my conconurse can get it and had the same problem.

but I can also build from the repo's master branch and use that resulting
image fine.

have you happend to try using the docker hub image yet ?

~dkohl

**Comment by Typositoire** [comment]
Ill check it out when I get home

**Comment by Typositoire** [comment]
Can you try with latest it should be the same image (as per docker hub)

**Comment by Typositoire** [comment]
Pulling the tag from both my office network and home works.

```
v1.12.0: Pulling from typositoire/concourse-helm3-resource
aad63a933944: Already exists 
332242dc504d: Already exists 
79e6c670afa2: Already exists 
787307b042e9: Pull complete 
0e20ba4d2e03: Pull complete 
99ec159e5fc1: Pull complete 
4e612c27c102: Pull complete 
563c4204666c: Pull complete 
7cea13c229df: Pull complete 
50a95b798d04: Pull complete 
Digest: sha256:87285a2cf5dfde0e28f2533a60641b3e490ab081e618f6184d349404be12fea2
Status: Downloaded newer image for typositoire/concourse-helm3-resource:v1.12.0
docker.io/typositoire/concourse-helm3-resource:v1.12.0
```

**Comment by cqwense** [comment]
the problem is not in downloading the image, but using it concourse -- i've
tried :latest tag as well, same results.

**Comment by cqwense** [comment]
I think I may have been falling victim to this:

https://github.com/concourse/concourse/discussions/5818

I deleted my pipeline and rebuilt it - and now it works /facepalm.

sorry.

**Comment by Typositoire** [comment]
Hey no worries!

**Pull request merged**
