### PR TITLE
Adding the create_namespace param

### PR DESCRIPTION
**Pull request by ts-mini**
As far as I can tell - there is no way to do this currently.  In helm 3 the namespace is expected to exist or else you must pass this flag

### CODE REVIEW

**Comment by ts-mini** [comment]
@Typositoire anything I need to do here to get this landed?

**Comment by Typositoire** [comment]
Sorry I'm on vacation :P I will be looking at everything tomorrow! Sorry for the delays!

**Comment by Typositoire** [comment]
And I'm bad. So vacationing is done :p I'm looking at this now

**Comment by Typositoire** [comment]
This should be soon availabled as `latest` and will be tagging it as `1.9.1` shortly.

**Pull request merged**
