### PR TITLE
adding `diff_opts` to allow adding aditional `helm diff` options.

### PR DESCRIPTION
**Pull request by duxing**
this can be helpful in situations where you have to add additional options to `diff` command.

e.g. if your `helm` chart contains `lookup` function, you need to specify `--dry-run=server` to `diff` command ([context](https://github.com/databus23/helm-diff/issues/449))

with `diff_opts`, it can be supported easily as the example in README.md

### CODE REVIEW

**Comment by duxing** [comment]
hi @Tang8330 ! can you take a look at this short PR when you have a chance?

**Comment by duxing** [comment]
@Typositoire can you take a look if you have a chance?

**Review by Tang8330 — APPROVED** [review]

**Comment by Tang8330** [comment]
Sorry @duxing, code lgtm

**Comment by duxing** [comment]
@Tang8330 sry I forgot to bump version, can you re-review?

**Review by Tang8330 — APPROVED** [review]

**Comment by duxing** [comment]
@Tang8330 sry to bother you again, if it's okay to you, can you help me merge the PR?

> Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.

**Pull request merged**
