### PR TITLE
Set helm upgrade history-max to 10 releases

### PR DESCRIPTION
**Pull request by ThibaultDelaune-pro**
Helm has this option set to 10 by default (cf. https://helm.sh/docs/helm/helm_upgrade/). So why setting another value in this concourse resource?

The problem is that in my organisation, nobody overwrite this setting and we have thousands of helm secrets persisting...

### CODE REVIEW

**Comment by Typositoire** [comment]
Concourse: Version bump found.

**Review by roux-jerome — APPROVED** [review]

**Review by roux-jerome — APPROVED** [review]

**Review by guidecayeux — APPROVED** [review]

**Review by PAM-PE — APPROVED** [review]

**Review by Berber31 — APPROVED** [review]

**Comment by roux-jerome** [comment]
@Typositoire an other intersting pull request

**Comment by Tang8330** [comment]
Agreed, nice feature.

**Review by Tang8330 — APPROVED** [review]

**Comment by Tang8330** [comment]
@Typositoire Looks like CI checks are hanging and there's no way to bypass.

**Comment by Typositoire** [comment]
Concourse: Version bump found.

**Pull request merged**
